# Generated by Django 2.2.17 on 2020-12-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20201210_0819"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="hgfghfhg",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hgfhgghf",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hgjgjh",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hgjhgjhg",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hgvhgjgjhgjh",
        ),
    ]
